In [1]:
import numpy as np
from scipy.spatial import ConvexHull
from collections import defaultdict
import numpy.linalg as LA

def create_vector(a,b,step):
    new_vec = []
    curr_val = a
    while curr_val < b:
        new_vec.append(curr_val)
        curr_val += step
    return new_vec

def linear_transform(start, end, time):
    
    return time * end + (1 - time) * start

def transform_to_3d_under_basis(set_of_points, basis):

    transformed = []
    for new_point in set_of_points:
        transformed_point = np.zeros(3)
        for coord, basis_vec in zip(new_point, basis):        
            transformed_point += coord * basis_vec
        transformed.append(transformed_point)

    return np.array(transformed)

import plotly.graph_objs as go
from plotly.offline import iplot
T = create_vector(0,1,0.001)

## Get the Wasserstein Ball under Discrete Metric in $\Delta_{n - 1}$ centered at 0

In [2]:
# # Hardy Weinburg

# d = 1
# n = 3
# var('p_0, p_1, p_2')
# mu = np.random.rand(n)
# mu /= LA.norm(mu)
# R.<p_0, p_1, p_2> = PolynomialRing(QQ, order = 'lex')
# Differentials = [p_0, p_1, p_2]
# P_translated = np.array(Differentials) - np.array(mu)
# G = [p_1^2-4*p_0*p_2]

# L_1_metric = [[0,1,2],[0,0,1]]
# discrete_metric = [[0,1,1],[0,0,1]]

# distance_metic = discrete_metric

In [3]:
# # Twisted Cubic

# d = 1
# n = 4
# var('p_0, p_1, p_2, p_3')
# mu = np.random.rand(n)
# mu /= LA.norm(mu)
# R.<p_0, p_1, p_2, p_3> = PolynomialRing(QQ, order = 'lex')
# Differentials = [p_0, p_1, p_2, p_3]
# P_translated = np.array(Differentials) - np.array(mu)
# G = [3*p_0*p_2-p_1^2, 3*p_1*p_3-p_2^2, 9*p_0*p_3-p_1*p_2]

# L_1_metric = [[0,1,2,3],[0,0,1,2],[0,0,0,1]]
# discrete_metric = [[0,1,1,1],[0,0,1,1],[0,0,0,1]]

# distance_metic = discrete_metric

In [4]:
# # Twisted Quartic

# d = 1
# n = 5
# var('p_0, p_1, p_2, p_3, p_4')
# mu = np.random.rand(n)
# mu /= LA.norm(mu)
# R.<p_0, p_1, p_2, p_3, p_4> = PolynomialRing(QQ, order = 'lex')
# Differentials = [p_0, p_1, p_2, p_3, p_4]
# P_translated = np.array(Differentials) - np.array(mu)
# defining_eqns = matrix(R, [[p_0, p_1/4, p_2/6, p_3/4],[p_1/4, p_2/6, p_3/4,p_4]])
# G = defining_eqns.minors(2)

# L_1_metric = [[0,1,2,3,4],[0,0,1,2,3],[0,0,0,1,2],[0,0,0,0,1]]
# discrete_metric = [[0,1,1,1,1],[0,0,1,1,1],[0,0,0,1,1],[0,0,0,0,1]]

# distance_metic = L_1_metric

In [5]:
# #Twisted Quintic

# d = 1
# n = 6
# var('p_0, p_1, p_2, p_3, p_4, p5')
# mu = np.random.rand(n)
# mu /= LA.norm(mu)
# R.<p_0, p_1, p_2, p_3, p_4, p_5> = PolynomialRing(QQ, order = 'lex')
# Differentials = [p_0, p_1, p_2, p_3, p_4, p_5]
# P_translated = np.array(Differentials) - np.array(mu)
# defining_eqns = matrix(R, [[p_0, p_1/5, p_2/10, p_3/10, p_4/5],[p_1/5, p_2/10, p_3/10,p_4/5, p_5]])
# G = defining_eqns.minors(2)

# L_1_metric = [[0,1,2,3,4,5],[0,0,1,2,3,4],[0,0,0,1,2,3],[0,0,0,0,1,2],[0,0,0,0,0,1]]
# discrete_metric =  [[0,1,1,1,1,1],[0,0,1,1,1,1],[0,0,0,1,1,1],[0,0,0,0,1,1],[0,0,0,0,0,1]]

# distance_metic = discrete_metric

In [6]:
#Twisted Sextic

d = 1
n = 7
var('p_0, p_1, p_2, p_3, p_4, p5, p6')
mu = np.random.rand(n)
mu /= LA.norm(mu)
R.<p_0, p_1, p_2, p_3, p_4, p_5, p_6> = PolynomialRing(QQ, order = 'lex')
Differentials = [p_0, p_1, p_2, p_3, p_4, p_5, p_6]
P_translated = np.array(Differentials) - np.array(mu)
defining_eqns = matrix(R, [[p_0, p_1/6, p_2/15, p_3/20, p_4/15, p_5/6],[p_1/6, p_2/15, p_3/20,p_4/15, p_5/6, p_6]])
G = defining_eqns.minors(2)

L_1_metric = [[0,1,2,3,4,5,6],[0,0,1,2,3,4,5],[0,0,0,1,2,3,4],[0,0,0,0,1,2,3],[0,0,0,0,0,1,2],[0,0,0,0,0,0,1]]
discrete_metric =  [[0,1,1,1,1,1,1],[0,0,1,1,1,1,1],[0,0,0,1,1,1,1],[0,0,0,0,1,1,1],[0,0,0,0,0,1,1],[0,0,0,0,0,0,1]]

distance_metic = L_1_metric

In [7]:
# #Twisted Septic

# d = 1
# n = 8
# mu = np.random.rand(n)
# mu /= LA.norm(mu)
# R.<p_0, p_1, p_2, p_3, p_4, p_5, p_6, p_7> = PolynomialRing(QQ, order = 'lex')
# Differentials = [p_0, p_1, p_2, p_3, p_4, p_5, p_6, p_7]
# P_translated = np.array(Differentials) - np.array(mu)
# defining_eqns = matrix(R, [[p_0, p_1/7, p_2/21, p_3/35, p_4/35, p_5/21, p_6/7],[p_1/7, p_2/21, p_3/35,p_4/35, p_5/21, p_6/7, p_7]])
# G = defining_eqns.minors(2)

In [8]:
A = []

for i in range(n):
    for j in range(n):
        if i < j:
            v = np.zeros(n + 1)
            v[0] = 1
            v[i + 1] = 1 / distance_metic[i][j]
            v[j + 1] = -1 / distance_metic[i][j]
            A.append(v)
            v = np.zeros(n + 1)
            v[0] = 1
            v[i + 1] = -1 / distance_metic[i][j]
            v[j + 1] = 1 / distance_metic[i][j]
            A.append(v)

In [9]:
A

[array([ 1.,  1., -1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 1., -1.,  1.,  0.,  0.,  0.,  0.,  0.]),
 array([ 1. ,  0.5,  0. , -0.5,  0. ,  0. ,  0. ,  0. ]),
 array([ 1. , -0.5,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ]),
 array([ 1.        ,  0.33333333,  0.        ,  0.        , -0.33333333,
         0.        ,  0.        ,  0.        ]),
 array([ 1.        , -0.33333333,  0.        ,  0.        ,  0.33333333,
         0.        ,  0.        ,  0.        ]),
 array([ 1.  ,  0.25,  0.  ,  0.  ,  0.  , -0.25,  0.  ,  0.  ]),
 array([ 1.  , -0.25,  0.  ,  0.  ,  0.  ,  0.25,  0.  ,  0.  ]),
 array([ 1. ,  0.2,  0. ,  0. ,  0. ,  0. , -0.2,  0. ]),
 array([ 1. , -0.2,  0. ,  0. ,  0. ,  0. ,  0.2,  0. ]),
 array([ 1.        ,  0.16666667,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.16666667]),
 array([ 1.        , -0.16666667,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.16666667]),
 array([ 1.,  0.,  1., -1.,  0.,  0.,  0.,  0.])

In [10]:
n

7

In [11]:
c = np.ones((n + 1))
c[0] = 0

In [12]:
P = Polyhedron(ieqs=A, eqns=[c])

In [13]:
V = []
for v in P.Vrepresentation():
    V.append(v.vector())

In [14]:
V

[(-1.285714286, -2.285714286, -1.285714286, -0.2857142857, 0.7142857143, 1.714285714, 2.714285714),
 (-1.0, -2.0, -1.0, 0.0, 1.0, 2.0, 1.0),
 (-0.7142857143, -1.714285714, -0.7142857143, 0.2857142857, 1.285714286, 0.2857142857, 1.285714286),
 (-0.4285714286, -1.428571429, -0.4285714286, 0.5714285714, 1.571428571, 0.5714285714, -0.4285714286),
 (-0.4285714286, -1.428571429, -0.4285714286, 0.5714285714, -0.4285714286, 0.5714285714, 1.571428571),
 (-0.1428571429, -1.142857143, -0.1428571429, 0.8571428571, -0.1428571429, 0.8571428571, -0.1428571429),
 (0.1428571429, -0.8571428571, 0.1428571429, 1.142857143, 0.1428571429, -0.8571428571, 0.1428571429),
 (0.4285714286, -0.5714285714, 0.4285714286, 1.428571429, 0.4285714286, -0.5714285714, -1.571428571),
 (-0.1428571429, -1.142857143, -0.1428571429, -1.142857143, -0.1428571429, 0.8571428571, 1.857142857),
 (0.1428571429, -0.8571428571, 0.1428571429, -0.8571428571, 0.1428571429, 1.142857143, 0.1428571429),
 (0.4285714286, -0.5714285714, 0.42857

In [15]:
B = []

for k in range(len(V)):
    curr_vec = [1]
    for v in V[k]:
        curr_vec.append(-v)
    B.append(curr_vec)

In [16]:
P_star = Polyhedron(ieqs=B, eqns=[c])

In [17]:
D = []
for d in P_star.Vrepresentation():
    D.append(d.vector())

In [18]:
D

[(0.0, 0.0, 0.0, 0.0, 0.0, 1.0, -1.0),
 (0.0, 0.0, 0.0, 1.0, -1.0, 0.0, 0.0),
 (0.0, 0.0, 1.0, -1.0, 0.0, 0.0, 0.0),
 (0.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0),
 (1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0),
 (0.0, 0.0, 0.0, 0.0, 1.0, -1.0, 0.0),
 (0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 1.0),
 (0.0, 0.0, 0.0, 0.0, -1.0, 1.0, 0.0),
 (0.0, 0.0, 0.0, -1.0, 1.0, 0.0, 0.0),
 (0.0, 0.0, -1.0, 1.0, 0.0, 0.0, 0.0),
 (0.0, -1.0, 1.0, 0.0, 0.0, 0.0, 0.0),
 (-1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0)]

In [19]:
for i in range(n):
    print(i, len(P_star.faces(i)))

0 12
1 60
2 160
3 240
4 192
5 64
6 1


## Solve the problem for every vertex, edge and face and extract the algebraic degree

In [20]:
algebraic_degrees = []

for face in P_star.faces(n - 3):
    curr_vectors = []
    for v_index in face.ambient_V_indices():
        vertex = P_star.Vrepresentation(v_index)
        curr_vectors.append(vertex)
        
    curr_normal = np.mean(curr_vectors,axis=0)
    for d in D:
        flag = 1
        for vec in curr_vectors:
            if np.dot(d, vec) != 1:
                flag = 0
                
        if flag == 1:
            curr_normal = np.copy(d)
        
    Q_list = []
    for vec in curr_vectors: 
        for i in range(n):
            Q_list.append(vec[i])
        
    B = Matrix(len(curr_vectors),n,Q_list)
    basis = B.right_kernel().basis()
    
    M_list = []
    rows = 0
    for v in curr_normal:
        M_list.append(v)
    rows += 1
        
    for g in G: 
        for differential in Differentials:
            M_list.append(g.derivative(differential))
        rows += 1
    
    for i in range(n):
        M_list.append(1)
    rows += 1
    
    for vec in basis: 
        np_vec = np.array(vec)
        for i in range(n):
            M_list.append(np_vec[i])
        rows += 1
    
    intersection_mu_L_F = []
    for vec in basis: 
        intersection_mu_L_F.append(np.array(vec) @ P_translated)
    
    for g in G: 
        intersection_mu_L_F.append(g)
    
    I = R.ideal(intersection_mu_L_F)
    M = Matrix(R,rows,n,M_list)

    J = I
    
    algebraic_degrees.append(J.vector_space_dimension())
    
print(min(algebraic_degrees))
print(max(algebraic_degrees))


6
6


In [21]:
algebraic_degrees = []

for face in P_star.faces(n - 2):
    curr_vectors = []
    for v_index in face.ambient_V_indices():
        vertex = P_star.Vrepresentation(v_index)
        curr_vectors.append(vertex)
    
    curr_normal = np.mean(curr_vectors,axis=0)
    for d in D:
        flag = 1
        for vec in curr_vectors:
            if np.dot(d, vec) != 1:
                flag = 0
                
        if flag == 1:
            curr_normal = np.copy(d)
    
    Q_list = []
    for vec in curr_vectors: 
        for i in range(n):
            Q_list.append(vec[i])
        
    B = Matrix(len(curr_vectors),n,Q_list)
    basis = B.right_kernel().basis()
    
    M_list = []
    rows = 0
    for v in curr_normal:
        M_list.append(v)
    rows += 1
        
    for g in G: 
        for differential in Differentials:
            M_list.append(g.derivative(differential))
        rows += 1
    
    for i in range(n):
        M_list.append(1)
    rows += 1
    
    for vec in basis: 
        np_vec = np.array(vec)
        for i in range(n):
            M_list.append(np_vec[i])
        rows += 1
    
    intersection_mu_L_F = []
    for vec in basis: 
        intersection_mu_L_F.append(np.array(vec) @ P_translated)
    
    for g in G: 
        intersection_mu_L_F.append(g)
    
    I = R.ideal(intersection_mu_L_F)
    M = Matrix(R,rows,n,M_list)
    
    J = I + M.minors(n)
    
    algebraic_degrees.append(J.vector_space_dimension())
    
print(min(algebraic_degrees))
print(max(algebraic_degrees))

KeyboardInterrupt: 

In [22]:
algebraic_degrees

[4, 5, 5, 5, 5, 5, 5, 5]